import Head from 'next/head'
import Link from 'next/link'
import React,{useState} from 'react'
import {pokedexApi} from '../api/pokedexApi'

export default function Home() {
  const [paguina, setCategoria] = useState()
  const [pokemon, setPokemon] = useState([])
    const handleBusqueda = () => {
        const httpRequest = pokedexApi.get(`/pokemon/${paguina}`)
        httpRequest.then((res) => {
          console.log(res.data)
          setPokemon(res.data.results)
        })
    }
    
    console.log(pokemon)
    
  return (
    <>
      <Head>
        <title>pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
      
        <div className="container">
          <div className="row mt-4">
          {
                pokemon.map((pokemones: any, index: number) => (
                  
                ))
            }
          </div>
        </div>
      </main>
    </>
  )
}
