import Head from 'next/head'
import Link from 'next/link'
import React,{useState} from 'react'
import {pokedexApi} from './api/pokedexApi'

export default function Home() {
  const [paguina, setCategoria] = useState()
  const [pokemon, setPokemon] = useState([])
  const [info,setinfo]=useState([])
    const handleBusqueda = () => {
        const httpRequest = pokedexApi.get(`/pokemon/${paguina}`)
        const httpInfo = pokedexApi.get(`pokemon-form/1/`)
        httpRequest.then((res) => {
          console.log(res.data)
          setPokemon(res.data.results)
        })
        httpInfo.then((res) => {
          console.log(res.data)
          setinfo(res.data.results)
        })
    }
    console.log(info)
    console.log(pokemon)
    
  return (
    <>
      <Head>
        <title>pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>

<div className="container mt-5">
  <div className="row">
    <div className="col">
      <select onChange={(e) => setCategoria(e.target.value)} className="form-select" aria-label="Default select example">
                  <option value="?offset=0&limit=20">paguina 0</option>
                  <option value="?offset=20&limit=20">paguina 1</option>
                  <option value="?offset=40&limit=20">paguina 2</option>
                  <option value="?offset=60&limit=20">paguina 3</option>
                  <option value="?offset=80&limit=20">paguina 4</option>
                  <option value="?offset=100&limit=20">paguina 5</option>
                  <option value="?offset=120&limit=20">paguina 6</option>
        </select>
        <button onClick={handleBusqueda} className="mt-3 btn btn-success">Buscar</button>
    </div>
  </div>
</div>
      
        <div className="container">
          <div className="row mt-4">
          {
                pokemon.map((pokemones: any, index: number) => (
                  <div className="col" key={index}>
                    <div className="card mt-4">
                    <div className="card-body">
                    <img src="img/img1.jpeg" className="card-img-top" alt="..."/>
                      <h5 className="card-title fw-lighter text-decoration-underline text-uppercase mt-4">{pokemones.name}</h5>
                    </div>

                    </div>
                  </div>
                ))
            }
          </div>
        </div>
      </main>
    </>
  )
}
